### ISSUE TITLE
Determinate help output ordering

### ISSUE THREAD

**Issue by loganwright** [vapor/console-kit#119]
help output order of commands is random or inconsistent each time, since it's a dictionary, maybe should be alphabetical?

**Comment by KyleLeneau** [comment]
@calebkleveter Seems like an easy for me and I have seen this before, do you have a preference here? We could either do alphabetical or try to keep it as order as defined by dev (would take some more engineering though).

**Comment by tanner0101** [comment]
Alphabetical order seems like a good option since it wouldn't require breaking changes to the API. Although it's possible that we could utilize `ExpressibleByDictionaryLiteral` to keep the dev's ordering without breaking API, too. 

`ExpressibleByDictionaryLiteral` gives you the `(String, T)...` expression of the dictionary which we can store internally as `[(String, T)]` preserving ordering.

**Comment by MrLotU** [comment]
Closed due to #136
